security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthenticator
            logout:
                path: app_logout
                target: app_home  # Redirige a la página principal tras logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # always_remember_me: true  # Descomenta si quieres que siempre esté activo

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/cliente, roles: ROLE_USER }
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10